/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedCoursRouteImport } from './routes/_authenticated/cours'
import { Route as AuthenticatedExamensRouteImport } from './routes/_authenticated/examens'
import { Route as AuthenticatedExercicesRouteImport } from './routes/_authenticated/exercices'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
import { Route as AuthenticatedProgressionRouteImport } from './routes/_authenticated/progression'
import { Route as AuthenticatedRevisionsRouteImport } from './routes/_authenticated/revisions'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedTachesRouteImport } from './routes/_authenticated/taches'
import { Route as AuthenticatedMatieresIndexRouteImport } from './routes/_authenticated/matieres.index'
import { Route as AuthenticatedMatieresSubjectIdRouteImport } from './routes/_authenticated/matieres.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursRoute = AuthenticatedCoursRouteImport.update({
  id: '/cours',
  path: '/cours',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamensRoute = AuthenticatedExamensRouteImport.update({
  id: '/examens',
  path: '/examens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExercicesRoute = AuthenticatedExercicesRouteImport.update({
  id: '/exercices',
  path: '/exercices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressionRoute =
  AuthenticatedProgressionRouteImport.update({
    id: '/progression',
    path: '/progression',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRevisionsRoute = AuthenticatedRevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTachesRoute = AuthenticatedTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatieresIndexRoute =
  AuthenticatedMatieresIndexRouteImport.update({
    id: '/matieres/',
    path: '/matieres/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatieresSubjectIdRoute =
  AuthenticatedMatieresSubjectIdRouteImport.update({
    id: '/matieres/$subjectId',
    path: '/matieres/$subjectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/cours': typeof AuthenticatedCoursRoute
  '/examens': typeof AuthenticatedExamensRoute
  '/exercices': typeof AuthenticatedExercicesRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/revisions': typeof AuthenticatedRevisionsRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/matieres/$subjectId': typeof AuthenticatedMatieresSubjectIdRoute
  '/matieres/': typeof AuthenticatedMatieresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/cours': typeof AuthenticatedCoursRoute
  '/examens': typeof AuthenticatedExamensRoute
  '/exercices': typeof AuthenticatedExercicesRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/revisions': typeof AuthenticatedRevisionsRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/matieres/$subjectId': typeof AuthenticatedMatieresSubjectIdRoute
  '/matieres': typeof AuthenticatedMatieresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/cours': typeof AuthenticatedCoursRoute
  '/_authenticated/examens': typeof AuthenticatedExamensRoute
  '/_authenticated/exercices': typeof AuthenticatedExercicesRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/progression': typeof AuthenticatedProgressionRoute
  '/_authenticated/revisions': typeof AuthenticatedRevisionsRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/taches': typeof AuthenticatedTachesRoute
  '/_authenticated/matieres/$subjectId': typeof AuthenticatedMatieresSubjectIdRoute
  '/_authenticated/matieres/': typeof AuthenticatedMatieresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistant'
    | '/cours'
    | '/examens'
    | '/exercices'
    | '/parametres'
    | '/planning'
    | '/progression'
    | '/revisions'
    | '/tableau-de-bord'
    | '/taches'
    | '/matieres/$subjectId'
    | '/matieres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assistant'
    | '/cours'
    | '/examens'
    | '/exercices'
    | '/parametres'
    | '/planning'
    | '/progression'
    | '/revisions'
    | '/tableau-de-bord'
    | '/taches'
    | '/matieres/$subjectId'
    | '/matieres'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistant'
    | '/_authenticated/cours'
    | '/_authenticated/examens'
    | '/_authenticated/exercices'
    | '/_authenticated/parametres'
    | '/_authenticated/planning'
    | '/_authenticated/progression'
    | '/_authenticated/revisions'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/taches'
    | '/_authenticated/matieres/$subjectId'
    | '/_authenticated/matieres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cours': {
      id: '/_authenticated/cours'
      path: '/cours'
      fullPath: '/cours'
      preLoaderRoute: typeof AuthenticatedCoursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examens': {
      id: '/_authenticated/examens'
      path: '/examens'
      fullPath: '/examens'
      preLoaderRoute: typeof AuthenticatedExamensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercices': {
      id: '/_authenticated/exercices'
      path: '/exercices'
      fullPath: '/exercices'
      preLoaderRoute: typeof AuthenticatedExercicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progression': {
      id: '/_authenticated/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof AuthenticatedProgressionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisions': {
      id: '/_authenticated/revisions'
      path: '/revisions'
      fullPath: '/revisions'
      preLoaderRoute: typeof AuthenticatedRevisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taches': {
      id: '/_authenticated/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof AuthenticatedTachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matieres/': {
      id: '/_authenticated/matieres/'
      path: '/matieres'
      fullPath: '/matieres/'
      preLoaderRoute: typeof AuthenticatedMatieresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matieres/$subjectId': {
      id: '/_authenticated/matieres/$subjectId'
      path: '/matieres/$subjectId'
      fullPath: '/matieres/$subjectId'
      preLoaderRoute: typeof AuthenticatedMatieresSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCoursRoute: typeof AuthenticatedCoursRoute
  AuthenticatedExamensRoute: typeof AuthenticatedExamensRoute
  AuthenticatedExercicesRoute: typeof AuthenticatedExercicesRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedProgressionRoute: typeof AuthenticatedProgressionRoute
  AuthenticatedRevisionsRoute: typeof AuthenticatedRevisionsRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedTachesRoute: typeof AuthenticatedTachesRoute
  AuthenticatedMatieresSubjectIdRoute: typeof AuthenticatedMatieresSubjectIdRoute
  AuthenticatedMatieresIndexRoute: typeof AuthenticatedMatieresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCoursRoute: AuthenticatedCoursRoute,
  AuthenticatedExamensRoute: AuthenticatedExamensRoute,
  AuthenticatedExercicesRoute: AuthenticatedExercicesRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedProgressionRoute: AuthenticatedProgressionRoute,
  AuthenticatedRevisionsRoute: AuthenticatedRevisionsRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedTachesRoute: AuthenticatedTachesRoute,
  AuthenticatedMatieresSubjectIdRoute: AuthenticatedMatieresSubjectIdRoute,
  AuthenticatedMatieresIndexRoute: AuthenticatedMatieresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
