/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedMatieresRouteImport } from './routes/_authenticated/matieres'
import { Route as AuthenticatedTachesRouteImport } from './routes/_authenticated/taches'
import { Route as AuthenticatedMatieresSubjectIdRouteImport } from './routes/_authenticated/matieres.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMatieresRoute = AuthenticatedMatieresRouteImport.update({
  id: '/matieres',
  path: '/matieres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTachesRoute = AuthenticatedTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatieresSubjectIdRoute =
  AuthenticatedMatieresSubjectIdRouteImport.update({
    id: '/$subjectId',
    path: '/$subjectId',
    getParentRoute: () => AuthenticatedMatieresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/matieres': typeof AuthenticatedMatieresRouteWithChildren
  '/taches': typeof AuthenticatedTachesRoute
  '/matieres/$subjectId': typeof AuthenticatedMatieresSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/matieres': typeof AuthenticatedMatieresRouteWithChildren
  '/taches': typeof AuthenticatedTachesRoute
  '/matieres/$subjectId': typeof AuthenticatedMatieresSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/matieres': typeof AuthenticatedMatieresRouteWithChildren
  '/_authenticated/taches': typeof AuthenticatedTachesRoute
  '/_authenticated/matieres/$subjectId': typeof AuthenticatedMatieresSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/matieres' | '/taches' | '/matieres/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/matieres' | '/taches' | '/matieres/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/matieres'
    | '/_authenticated/taches'
    | '/_authenticated/matieres/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/matieres': {
      id: '/_authenticated/matieres'
      path: '/matieres'
      fullPath: '/matieres'
      preLoaderRoute: typeof AuthenticatedMatieresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taches': {
      id: '/_authenticated/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof AuthenticatedTachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matieres/$subjectId': {
      id: '/_authenticated/matieres/$subjectId'
      path: '/$subjectId'
      fullPath: '/matieres/$subjectId'
      preLoaderRoute: typeof AuthenticatedMatieresSubjectIdRouteImport
      parentRoute: typeof AuthenticatedMatieresRoute
    }
  }
}

interface AuthenticatedMatieresRouteChildren {
  AuthenticatedMatieresSubjectIdRoute: typeof AuthenticatedMatieresSubjectIdRoute
}

const AuthenticatedMatieresRouteChildren: AuthenticatedMatieresRouteChildren = {
  AuthenticatedMatieresSubjectIdRoute: AuthenticatedMatieresSubjectIdRoute,
}

const AuthenticatedMatieresRouteWithChildren =
  AuthenticatedMatieresRoute._addFileChildren(
    AuthenticatedMatieresRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMatieresRoute: typeof AuthenticatedMatieresRouteWithChildren
  AuthenticatedTachesRoute: typeof AuthenticatedTachesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMatieresRoute: AuthenticatedMatieresRouteWithChildren,
  AuthenticatedTachesRoute: AuthenticatedTachesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
